name: Release

on:
   push:
     tags:
       - 'v*'

# https://stackoverflow.com/questions/63887031/build-docker-image-locally-in-github-actions-using-docker-build-push-action

jobs:
  pypi:
    name: Release To PyPi
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          with:
              driver: docker
        - name: build
          uses: docker/build-push-action@v2
          with:
              context: release
              push: false
              tags: pypi_release:latest
              file: release/Dockerfile

        - name: upload to pypi
          run: |
            docker run pypi_release:latest /bin/bash -i -c 'source ~/.bashrc; twine upload --skip-existing -u __token__ -p ${{ secrets.PYPI_TOKEN_VOXBLOXPY }} $HOME/voxbloxpy/dist/*'
