name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: update submodule
              run: git submodule update --init --depth=1

            - name: Install apt packages
              run: |
                  sudo apt-get install libeigen3-dev libgtest-dev
                  sudo apt-get install libgflags-dev libgoogle-glog-dev libprotobuf-dev

            - name: Build
              run: |
                  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig"
                  mkdir build
                  cd build
                  cmake -DBUILD_TEST=ON ..
                  make

            - name: Test c++
              run: |
                  cd build
                  ctest --verbose
