name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: update submodule
              run: git submodule update --init --depth=1

            - name: Install apt packages
              run: |
                  sudo apt-get install libeigen3-dev libgtest-dev
                  sudo apt-get install libgflags-dev libgoogle-glog-dev libprotobuf-dev

            - name: Build
              run: |
                  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig"
                  mkdir build
                  cd build
                  cmake -DBUILD_TEST=ON ..
                  make

            - name: Test c++
              run: |
                  cd build
                  ctest --verbose

            - name: Build python module
              run: |
                  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig"
                  pip3 install scikit-build
                  pip3 install  .

            - name: Test python module
              run: |
                  python3 example/ground_truth_cylinder.py
                  python3 example/incremetal_update.py
                  pip3 install gdown
                  cd example/dataset && bash ./download_dataset.sh && cd ../..
                  python3 example/real_data.py
